sudo: false

addons:
  apt_packages:
    - lib32stdc++6

env:
  global:
    - SCRIPTING=addons/sourcemod/scripting/
    - PLUGINS=addons/sourcemod/plugins
    - SOURCEMOD_MAJOR=1.7
    - SOURCEMOD_MINOR=1.7.3-git5258
    - SCRIPT=build-env/addons/sourcemod/scripting/compile.sh

before_install:
  - mkdir build-env

install:
  - cd build-env
  - wget http://www.sourcemod.net/smdrop/$SOURCEMOD_MAJOR/sourcemod-$SOURCEMOD_MINOR-linux.tar.gz
  - tar -xzvf sourcemod-$SOURCEMOD_MINOR-linux.tar.gz
  - wget https://github.com/whocodes/serversys/archive/master.zip
  - unzip master.zip
  - chmod -R 777 serversys-master
  - cp -rv serversys-master/. .
  - find build-env/addons/sourcemod/scripting/ -name "*.sp" -type f -delete
  - cd ../
  - cp -rv $SCRIPTING/. build-env/addons/sourcemod/scripting/

before_script:
  - chmod +rx build-env/addons/sourcemod/scripting/spcomp
  - chmod +rx $SCRIPT

script:
  - ./$SCRIPT

after_success:
  - mkdir $PLUGINS
  - cp -rv build-env/addons/sourcemod/scripting/compiled/. $PLUGINS
  - rm -r build-env
  - zip -9rq $TRAVIS_COMMIT.zip addons
  - find $TRAVIS_COMMIT.zip -type f -exec curl --user $FTPUSER:$FTPPASS --ftp-create-dirs -T {} ftp://$FTPPATH/whocodes/public/git-build/serversys-umsghack/{} \;
